version: '3'

services:
  update-server-app:
    build: ./update-server-app
    image: update-server-app:python
    container_name: update-server-app
    ports:
      - 8888:17000
    volumes:
      - ./update-server-app/src/packages:/packages
    environment:
      - TORNADO_PORT=17000
      - APK_PACKAGES=/packages

