version: '3'

services:
  ngnix:
    build: ./nginx
    image: update-server/nginx:latest
    container_name: update-server-nginx
    ports:
      - 8888:${NGINX_PORT-80}
    volumes:
      - ./update-server-app/src/packages:/packages
      - ./log:/var/log
    envnironment:
      - NGINX_PORT=${NGINX_PORT-80}
    links:
      - supervisor

  supervisor:
    build: ./update-server-app
    image: update-server/supervisor:latest
    container_name: update-server-supervisor
    ports:
      - 13000-13003:13000-13003
    volumes:
      - ./update-server-app/src/packages:/packages
      - ./log:/var/log
