version: '3'

services:
  ngnix:
    build: ./nginx
    image: update-server-app:nginx
    container_name: update-server-nginx
    ports:
      - 8888:80
    volumes:
      - ./update-server-app/src/packages:/packages
      - ./log:/var/log
    environment:
      - UPDATE_SERVER_ADDRESS=update-server-supervisor
      - UPDATE_SERVER_PORT1=13000
      - UPDATE_SERVER_PORT2=13001
      - UPDATE_SERVER_PORT3=13002
      - UPDATE_SERVER_PORT4=13003
    links:
      - update-server-supervisor
    depends_on:
      - update-server-supervisor

  update-server-supervisor:
    build: ./update-server-app
    image: update-server-app:supervisor
    container_name: update-server-supervisor
    ports:
      - 13000-13003:13000-13003
    volumes:
      - ./update-server-app/src/packages:/packages
      - ./log:/var/log
    environment:
      - SUPERVISOR_START_PORT=13000
      - SUPERVISOR_PROCESSES=4
      - APK_PACKAGES=/packages
      - LOGS=/var/log