version: '3'

services:
  update-server-app:
    build: ./update-server-app
    image: update-server-app:python
    container_name: update-server-app
    ports:
      - 17000:8888
    environment:
      - TORNADO_PORT=17000
