version: '3'

services:

  update-server-supervisor:
    build: ./update-server-app
    image: update-server-app:supervisor
    container_name: update-server-supervisor
    ports:
      - 13000-13003:13000-13003
    volumes:
      - ./update-server-app/src/packages:/packages
      - ./update-server-app/src/log:/var/log
    environment:
      - SUPERVISOR_START_PORT=13000
      - SUPERVISOR_PROCESSES=4
      - APK_PACKAGES=/packages
      - LOGS=/var/log